

services:
  torbox-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: torbox-app
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    user: "1001:1001"  # nextjs user from Alpine image
    networks:
      - torbox-network

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'




networks:
  torbox-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: torbox-br0

volumes:
  torbox-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
