
services:
  torbox-app:
    image: ghcr.io/crazycacti/torbox-app:latest
    container_name: torbox-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.tbm.rule=Host(`${TORBOX_MANAGER_HOSTNAME?}`)"
    #   - "traefik.http.routers.tbm.entrypoints=websecure"
    #   - "traefik.http.routers.tbm.tls.certresolver=myresolver"
    #   - "traefik.http.routers.tbm.middlewares=authelia@docker"
